const $=s=>document.querySelector(s);let DATA={all_stocks:[]},tab='all',fav=new Set(JSON.parse(localStorage.getItem('idxpro_fav')||'[]'));
const fmt=n=>Number(n||0).toLocaleString('id-ID',{maximumFractionDigits:2});
function tf(s,k){return s.timeframes?.[k]||{}}
function scoreParts(s,k='daily'){let x=tf(s,k);return [['Trend',x.trend_score||0,25],['Momentum',x.momentum_score||0,20],['Volume',x.volume_score||0,15],['Technical',x.technical_score||0,15],['Risk',x.risk_score||0,15]]}
function cls(sig){return sig.replace(' ','_')}
function card(s){let k=$('#tf').value,x=tf(s,k), parts=scoreParts(s,k), is=fav.has(s.ticker);return `<article class="card" data-t="${s.ticker}"><button class="fav" title="Favorite">${is?'★':'☆'}</button><div class="score">${s.professional_score||0}<small>/100</small></div><div class="signal ${s.signal.split(' ')[0]}">${s.signal}</div><h2>${s.ticker}</h2><div class="tags"><span class="tag">${s.strategy}</span><span class="tag">MTF ${s.mtf_alignment||0}/3</span><span class="tag ${x.regime==='BULLISH'?'bull':x.regime==='BEARISH'?'bear':''}">${x.regime||'-'}</span></div><div class="bars">${parts.map(p=>`<div class="bar"><span>${p[0]}</span><div class="track"><div class="fill" style="width:${p[1]/p[2]*100}%"></div></div><b>${Math.round(p[1])}</b></div>`).join('')}</div><div class="pricegrid"><div><small>PRICE</small><br>${fmt(s.close)}</div><div class="risk"><small>STOP</small><br>${fmt(s.stop_loss)}</div><div><small>TP1</small><br>${fmt(s.take_profit_1)}</div><div><small>TP2</small><br>${fmt(s.take_profit_2)}</div><div><small>RSI</small><br>${fmt(x.rsi)}</div><div><small>RVOL</small><br>${fmt(x.rvol)}</div></div></article>`}
function render(){let q=$('#search').value.toUpperCase(),sig=$('#signal').value,a=DATA.all_stocks||[];a=a.filter(s=>(!q||(s.ticker+s.strategy+s.signal).toUpperCase().includes(q))&&(!sig||s.signal===sig));if(tab==='buy')a=a.filter(s=>/BUY/.test(s.signal));if(tab==='fav')a=a.filter(s=>fav.has(s.ticker));$('#grid').innerHTML=a.map(card).join('')||'<p>Tidak ada setup.</p>';document.querySelectorAll('.card').forEach(c=>{c.onclick=e=>{if(e.target.classList.contains('fav')){let t=c.dataset.t;fav.has(t)?fav.delete(t):fav.add(t);localStorage.setItem('idxpro_fav',JSON.stringify([...fav]));render();return}open(c.dataset.t)})}
function summary(){let a=DATA.all_stocks||[],buy=a.filter(s=>/BUY/.test(s.signal)).length,elite=a.filter(s=>s.signal==='ELITE BUY').length,avg=a.length?Math.round(a.reduce((n,s)=>n+(s.professional_score||0),0)/a.length):0;$('#summary').innerHTML=[['EMITEN',a.length],['BUY SETUP',buy],['ELITE',elite],['AVG SCORE',avg]].map(x=>`<div class="metric"><small>${x[0]}</small><b>${x[1]}</b></div>`).join('')}
function open(t){let s=DATA.all_stocks.find(x=>x.ticker===t);$('#detail').innerHTML=`<h1>${s.ticker} <small>${s.signal}</small></h1><p><b>Best Strategy:</b> ${s.strategy} · MTF alignment ${s.mtf_alignment}/3</p><h3>Multi-Timeframe Dashboard</h3><div class="tfgrid">${Object.entries(s.timeframes||{}).map(([k,x])=>x.error?`<div class="tfcard"><b>${k.toUpperCase()}</b><br>Data unavailable</div>`:`<div class="tfcard"><b>${k.toUpperCase()}</b><br><span class="${x.regime==='BULLISH'?'bull':x.regime==='BEARISH'?'bear':''}">${x.regime}</span><br>RSI ${fmt(x.rsi)} · ADX ${fmt(x.adx)}<br>RVOL ${fmt(x.rvol)}<br>MACD ${x.macd_bullish?'Bullish':'Bearish'}</div>`).join('')}</div><h3>Risk Plan</h3><div class="pricegrid"><div>Entry<br><b>${fmt(s.close)}</b></div><div class="risk">Stop<br><b>${fmt(s.stop_loss)}</b></div><div>TP1<br><b>${fmt(s.take_profit_1)}</b></div><div>TP2<br><b>${fmt(s.take_profit_2)}</b></div></div><p><small>Educational screener only. Gunakan position sizing, backtest, dan konfirmasi kondisi pasar.</small></p>`;$('#modal').showModal()}
async function load(){try{let r=await fetch('data.json?'+Date.now(),{cache:'no-store'});DATA=await r.json();localStorage.setItem('idxpro_data',JSON.stringify(DATA));toast('Data diperbarui')}catch(e){DATA=JSON.parse(localStorage.getItem('idxpro_data')||'{"all_stocks":[]}');toast('Offline: menggunakan cache terakhir')}$('#updated').textContent=DATA.last_updated||'Demo / cached data';summary();render()}
function toast(x){let e=$('#toast');e.textContent=x;e.style.display='block';setTimeout(()=>e.style.display='none',1800)}
['search','signal','tf'].forEach(i=>$('#'+i).addEventListener(i==='search'?'input':'change',render));$('#refresh').onclick=load;$('.close').onclick=()=>$('#modal').close();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});addEventListener('online',()=>$('#net').textContent='● ONLINE');addEventListener('offline',()=>$('#net').textContent='● OFFLINE');if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');load();
